# Data sources

We sourced our data from [Spotify's API](https://developer.spotify.com/documentation/web-api/guides/ ). Spotify manages its API and provides extensive documentation on its variables, etc. Generally speaking, the Spotify API is used by developers to collect information on musical artists, songs, albums, etc. The API provides data on specific artists - such as their followers, popularity, discography, etc. - and on the music in whatever form it is in (songs, albums, playlists). The data on the music includes audio features, such as 'danceability', 'energy', 'speechiness', 'key', and more. Clearly, many of the features in the Spotify API data are the output of Spotify's proprietary algorithms -- for example, how you measure "danceability" depends on a number of factors that Spotify have chosen at their discretiono. Another variable we used throughout our project was 'popularity'. Artists have a `popularity` rating, as do albums and songs. Spotify does not provide any specific details on how their algorithms calculate this metric, however we do know that it is dependent on number of listens as well as how recent those listens are. 

As with most API's, many of these metrics are updated continuously -- for example, an artist's number of followers will change, but the audio features of one of their songs will not. All of the information we are able to pull from the API is the latest data, i.e. we cannot see historical data, such as how an artist's `popularity` has changed over time. 

In this project we used the `SpotifyR` package to pull data from the API. `SpotifyR` is a very useful R wrapper for the Spotify Web API. The package was last updated in November 2021 and it contains a number of useful functions that streamlined the data collection process of this project. The primary functions we used were the following:

 * `get_genre_artists()`
    * This function pulls the most popular artists (as determined by Spotify) in a specific genre and market (country). We used this function to pull the 20 most popular rap and country artists across 8 different markets. Each row in this data equates to an artist.
*  `get_artist_top_tracks()`
    * This function allows you to pull the top/most popular tracks of an artist (you can choose the number of tracks). We fed in the artist id's from the `get_genre_artists()` data and got the top 10 tracks for each of the top 20 rap artists in each country -- around 200 tracks for each of the 8 countries country (1600 rap songs total). So in this dataset each row equates to a track/song. Each song has information on its release date, which album its in (if its on an album), its popularity, its duration, the artists on the track, whether it's explicit or not, and more. 
*   `get_audio_features()` 
    * This function was useful in getting the audio features of each track. Each track has audio data such as danceability, loudness, acousticness, energy, and more. 

After using these functions, we have a few main datasets. The rap and country datasets have around 1600 rows each and each row is a different song. Within these datasets, we have 200 songs for 8 countries, i.e. the top rappers and country artist's top songs. 
    
As stated earlier, the API does not provide historical data, which would have been useful in our analysis. Other than this shortcoming, there are no known problems with this data. Of course, when using the Spotify data for analysis, one must be cogniscent that many metrics are the results of Spotify's proprietary algorithms. 
    
    
    
    
    
    
    
    