# Results

```{r}
# Load Packages  ----------------------------------------------------------


library(spotifyr)
library(tidyverse)
library(plyr); library(dplyr)
library(redav)
library(GGally)
library(jsonlite)
library(ggridges)
library(plotly)
library(shape)
library(sf)
library(tmap)
library(mi)
library(jsonlite)


# Loading Data Files  ---------------------------------------------------------------------

rap_artists2_ = read.csv("rap_artists.csv")

rapcountry_full_ = read.csv("rapcountry_full.csv")

rap_4_ = read.csv("rap_4.csv")

rapcountry_4_ = read.csv("rapcountry_4.csv")

IndiaKorea_longer_ = read.csv("IndiaKorea_longer.csv")

audiofeatures_uskoreafrench_ = read.csv("audiofeatures_uskoreafrench.csv")


```


[SHORT INTRO]


```{r}
draw_biplot(rapcountry_full_[, c(9,28:38,45)], points = F) +
  geom_point(aes(color  = rapcountry_full_$genre))+
  scale_color_manual(values = c(2,1,3))+
  theme_minimal()
```

[DISCUSS BIPLOT]



```{r}

### Parallel Coordinates Plot 

GGally::ggparcoord(rapcountry_full_,
                   28:38,
                   alphaLines = .3, 
                   splineFactor = 10,
                   groupColumn = "genre") + theme_minimal()+
  scale_color_manual(values = c(2,3))+theme(axis.text.x = element_text(size = 5.8))
```

[PARALLEL COORDINATES]


```{r}
# Other Differences in Rap and Country ------------------------------------

ggplot(
  rapcountry_full_, 
  aes(x = popularity, y = explicit)
) + 
  geom_density_ridges(scale = 1) + 
  theme_ridges() +
  facet_wrap(~genre)
```


[RIDGE PLOT, EXPLICITNESS]


```{r}

####Proportion of top rap songs that are explicit per market
rapcountry_4_$Country = fct_reorder2(factor(rapcountry_4_$country), rapcountry_4_$genre == "rap", rapcountry_4_$explicitprop)

vcd::mosaic( explicit ~ genre + Country, rapcountry_4_,
             direction = c("h", "v", "h"),
             highlighting_fill = c("light blue","purple"),
             main = "Explicitness by Country and Genre" ,
 labeling_args =            list(rot_labels = c(bottom = 90,left = 0,
     right = 0), offset_varnames = c(right = 1), offset_labels = c(left = 0.35, right = 0.4)),
     margins = c(left = 5,right = 4, bottom = 3),
  set_labels=list(explicit = c("Clean", "Explicit"))
             ) 

```

[EXPLICITNESS ACROSS MARKETS]

```{r}
# Rap and Country across Markets, by Release Date ------------------------

rapcountry_4_$date = as.Date(rapcountry_4_$album.release_date, 
                     "%Y-%m-%d")
rapcountry_4_$country2 = fct_rev(factor(rapcountry_4_$country, 
                                levels = c("FR", "KR", "JP", "IN","GH",
                                           "US","GB","MX" )))

ggplot(data = rapcountry_4_) + 
  geom_histogram(aes(date,
                     y=..density..,
                     fill = genre)) + 
  geom_density(aes(x=date),
               col = "dark blue")+
  facet_grid(genre ~ country2,
             scales="free_y")+ 
  scale_x_date(date_labels = "'%y")+
  theme_minimal()+
  scale_fill_manual(values = c(2,3))
```

[LISTENING HISTORY BY RELEASE DATE]


```{r}
# India vs Korea ----------------------------------------------------------

ggplot(
  IndiaKorea_longer_, 
  aes(x = Value, y = genre)) + 
  geom_density_ridges() + 
  theme_ridges() +
  facet_grid(.~ factor(Metric, levels = c("Popularity", "Followers (in Thousands)")),
             scales = "free")
```

[DEMONSTRATING DIFFERENCE BETWEEN INDIAN AND KOREAN RAP INDUSTRIES]

```{r}
# stacked bar chart -- top rap artists per country by where they are based --------
  
ggplot(rap_artists2_, aes(x = fct_rev(fct_reorder(factor(country), 
                                                .x = localprop )), 
                        fill = local)) +
  geom_bar(position = "fill") +
  theme_minimal()+
  labs(x = "Country",
       y= "Proportion",
       title = "Top Rap Tracks in Each Country by Artist Location ",
       fill = "Is the Rapper Local\nto the Country?")+
  scale_y_continuous(labels = scales::percent)

```

[STACKED BAR CHART -- LOCAL ARTISTS]


```{r}
#####
ggplot(rap_artists2_, aes(x = fct_reorder(factor(country), .x =followers.total,.fun = mean), 
                        y = followers.total/1000000,
                        col = local)) +
  geom_point(alpha = 0.75)+
  coord_flip()+
  theme_linedraw()+
  labs(x = "Country", y = "Followers (MM)",
       title = "Spotify Following of Each Country's Top Rappers",
       col = "Is the Rapper Local\nto the Country?")
```

[# FOLLOWERS, WHERE THEY ARE FROM, ETC]


```{r}
# France, Korea, USA ------------------------------------------------------


draw_biplot(audiofeatures_uskoreafrench_[,c(2:12,14,20)], points = F) +
  geom_point(aes(color  = audiofeatures_uskoreafrench_$country))+
  scale_color_manual(values = c(1:16))+
  theme_minimal()

```

[FRANCE V KOREA]






