# Conclusion

This analysis was very interesting and exciting for us as music fans. First, it was fascinating to explore the technical features of a song and to see how music can be quantified and measured in terms of energy, joy, and danceability to name a few. We found that country and rap songs tend to be influenced by different features, however there is certainly overlap in other areas. For example, while country music may have higher acousticness and rap is more danceable, they vary in their valence (which is a measure of joy). We found it interesting to see how much variation there is across tracks in terms of tempo and energy, but factors like instrumentalness had little to no variation. All of this helped us set a baseline in our next explorations which largely focused on listening trends in these genres.

We made use of the popularity variable which helped serve as a proxy for listening trends across different markets in different industries. We uncovered interesting insights abroad, namely that foreign nations like France, Korea and Japan have taken American rap and created their own industries and sounds. We saw how these three countries mostly listen to very recent rap songs, and their most popular rappers are typically local. We also found that not only do French and Korean listeners have different listening trends to the United States' listeners (in that they mostly listen to very recently released songs), but French and Korean rappers also employ different techniques (in that their album tracks are shorter than their single tracks). Both of these facts reflects two very young and developing rap scenes, which are certainly growing in popularity and evolving with time.

However, on the flip side, it was also clear that other countries have not developed their own rap industries and almost exclusively listen to American rap music. In fact, when we looked into Indian rap for example, we found very low popularity/traction and the artists had very few followers. This is a very important statement for a population of over 1 billion people. We also looked at how these countries have differing listening patterns. For example, we saw that Korean and Japanese rap music, while very clearly a part of their respective pop cultures, have maintained the conservative elements of their societies. French rap, on the other hand, is mostly comprised of French artists who release explicit music. Clearly, explicit music is the norm in the West. This fact connects back to the analysis of the explicit country songs and how they were just as, if not more, popular than clean country songs. Finally, when we analyzed the younger, yet rapidly developing rap industries - particularly the French and Korean markets - we found a broad American influence and yet clearly each country had developed their own sound. It is interesting to see how this American music genre has spread across the globe and evolved to match the tastes of other cultures and societies. 

Although we certainly found significant value in the Spotify API, there were certainly limitations that we had to deal with. To start, Spotify did not provide extensive information on the artists - such as their age, nationality, language, etc. - and they did not provide any information on the Spotify listeners. Instead, we had to use popularity as a proxy for listening trends. Moreover, Spotify only provides the most recent/up-to-date information, as opposed to historical information that could be used to see changing trends and trajectories. Once again, we had to use what information was at our disposal, such as combining release dates and popularity, to understand the nature of the emerging rap industries worldwide.  









